### ISSUE TITLE
GitHub有个不要脸的抄了你的脚本

### ISSUE THREAD

**Issue by ghost** [fengyouchao/pysocks#9]
仓库地址：https://github.com/kkkyg/pysocks

无视你设置的Apache 2.0开源协议，随意抄袭。
请看到之后尽量寻找GitHub官方处理

**Comment by fengyouchao** [comment]
感谢反馈, 我已经在对方的Repo中发出了提醒, 如果对方没有反应, 我再考虑发起DMCA takedown
